### ISSUE TITLE
replace links to w3schools

### ISSUE THREAD

**Issue by groovecoder** [mdn/wp-promote-mdn#12]

**Comment by Mte90** [comment]
is not simple because w3c schools use different url respect to mdn.
and create a file with the association is a big job...

**Comment by groovecoder** [comment]
The implementation I had in mind was to over-write any links on the *phrases* and terms, not the urls. E.g., if there's a link for "JavaScript", change it from
```
<a href="http://www.w3schools.com/js/default.asp">JavaScript</a>
```
to
```
<a href="https://developer.mozilla.org/docs/JavaScript">JavaScript</a>
```

**Comment by Mte90** [comment]
ahhh so you refer to the term, uhm maybe the algorithm need to be improved to check if the term is contained in an anchor.

**Comment by Mte90** [comment]
I think that today the situation it is completely different so we can close that issues.
