### ISSUE TITLE
Support linking to IRC channels

### ISSUE THREAD

**Issue by a2sheppy** [mdn/wp-promote-mdn#31]
Would be awesome if uses of #mdn, #mdndev, and #devmo in text would automatically become irc://irc.mozilla.org/X links.

**Comment by Mte90** [comment]
uhm maybe is a problem, if the user have a plugin that transform the # terms in hastags on twitter will be a conflict.
Or for the same reason if write an hashtag of twitter will be transform on a irc channel of mozilla.

**Comment by Mte90** [comment]
maybe we can create a shortcode like [mozirc chan="#mdn"]

**Comment by Mte90** [comment]
Actually the page https://developer.mozilla.org/en-US/docs/Template:Promote-MDN used for get the links contain also this two channel.
```
#mdn, irc://irc.mozilla.org/mdn
#mdndev, irc://irc.mozilla.org/mdndev
```
So i update the page and close this ticket :-)

**Comment by Mte90** [comment]
Uhm i don't have the permission to edit this page.
@groovecoder can you add me to this page (https://developer.mozilla.org/en-US/profiles/Mte90)?

**Comment by groovecoder** [comment]
Unfortunately not. I (ab)used the `Template:` namespace for this feature, and there's a very limited set of users who are allowed to edit templates. We would have to file a bug to change the source page of the links to something else.

**Comment by Mte90** [comment]
uhm i want only to add #devmo in the page but i think that page need to be editable for add new things, but we can use a new ticket for that.

**Comment by groovecoder** [comment]
I added #devmo myself for now.

**Comment by a2sheppy** [comment]
#devmo is no longer open though; we moved to #mdn. So I don't think 
adding #devmo makes much sense, unless you've got it set up to send 
people to #mdn. But it really should simply not do anything.

> luke crouch <mailto:notifications@github.com>
> May 6, 2015 at 12:24 PM
>
> I added #devmo myself for now.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mdn/wp-promote-mdn/issues/31#issuecomment-99528717>.
>

-- 

Eric "Sheppy" Shepherd
http://www.sheppyware.net/
http://www.bitstampede.org/
