### ISSUE TITLE
Publish blogging activity to MDN profile

### ISSUE THREAD

**Issue by groovecoder** [mdn/wp-promote-mdn#45]
As a user of the WordPress plugin, I want to publish my blogging activity on my MDN profile.

(Note: This will require corresponding work on https://github.com/mozilla/kuma code)

**Comment by Mte90** [comment]
Which profile mdn?

**Comment by groovecoder** [comment]
Updated issue summary and description.

**Comment by Mte90** [comment]
There is no api for this :-/
https://developer.mozilla.org/en-US/docs/MDN/Kuma/API

**Comment by groovecoder** [comment]
Nope, no existing API. It would have to be developed on the MDN side too.
