### ISSUE TITLE
Update widget images

### ISSUE THREAD

**Issue by groovecoder** [mdn/wp-promote-mdn#50]
See https://developer.mozilla.org/en-US/docs/Project:MDN/Promote#Web_site_banner_images

**Comment by Mte90** [comment]
you can close this ticket

**Comment by groovecoder** [comment]
I guess the commit message needed to be "fix #50" to [automatically close](https://help.github.com/articles/closing-issues-via-commit-messages/) it.

**Comment by Mte90** [comment]
yes but i am not the owner of the repo, so i cannot close the ticket :-)

**Comment by groovecoder** [comment]
I think if you put "fix #50" into the commit message, it will automatically close the issue by virtue of my (repo owner) merging it.
