### ISSUE TITLE
Use proper capability string for add_options_page()

### ISSUE THREAD

**Issue by dnaber-de** [mdn/wp-promote-mdn#53]
The plugin triggers a notice in the backend:
```
Notice: has_cap was called with an argument that is deprecated since version 2.0! Usage of user levels by plugins and themes is deprecated. Use roles and capabilities instead. in /var/www/projects/wordpress/wp-includes/functions.php on line 3006
```
which comes from the wrong parameter in `add_options_page()` [here](https://github.com/groovecoder/wp-promote-mdn/blob/6557c4d835935a9a9424bd945d1ab9d6c54e2d4c/promote-mdn.php#L350):
```php
 function admin_menu()
    {
        add_options_page( 'Promote MDN Options', 'Promote MDN', 8, basename( __FILE__ ), array( &$this, 'handle_options' ) );
    }
```
The third [parameter](http://codex.wordpress.org/Function_Reference/add_options_page) must be a [capability](http://codex.wordpress.org/Roles_and_Capabilities#Capabilities) (string) like `manage_options`:
```php
 function admin_menu()
    {
        add_options_page( 'Promote MDN Options', 'Promote MDN', `manage_options`, basename( __FILE__ ), array( &$this, 'handle_options' ) );
    }
```

**Comment by Mte90** [comment]
you can close this ticket
