### ISSUE TITLE
Protocol documentation

### ISSUE THREAD

**Issue by karlcow** [mdn/wp-promote-mdn#59]
To help people porting the plugin to different system than WordPress and in different languages. It would be good to document the protocol used for communicating and the minimum requirements.

**Comment by groovecoder** [comment]
@karlcow - I started this in https://github.com/groovecoder/wp-promote-mdn/pull/65 but I'm not sure everything you want included in "protocol"? It's very simple - an HTTP request to [the raw Template:Promote-MDN page on MDN](https://developer.mozilla.org/en-US/docs/Template:Promote-MDN?raw=1) returns a CSV of terms/phrases and URLs.

**Comment by karlcow** [comment]
In the current list of features I see:

## Widget for sidebars with graphic/banner link

Not sure what it does.


## Automatic linking of key terms and phrases (defined on MDN itself) in posts and pages

OK this I guess I understand now.
1. Parses a raw text
2. Identify words separated by spaces
3. Autolink words which are identified in a fixed list of terms given by a `HTTP GET` to `https://developer.mozilla.org/en-US/docs/Template:Promote-MDN?raw=1`. The list format is 

```
JavaScript, JS, JS Documentation, JS Reference, https://developer.mozilla.org/docs/JavaScript
```
aka list of terms separated by commas and last item is the URL.

Note for developers: You might want to do HTTP caching and not request the list everytime.

## Ability to notify Mozilla Press and DevRel teams when publishing posts

How does it work?
automatic Ping? automatic Email? etc.

**Comment by Mte90** [comment]
The widget is a simple settings for show on the frontend a banner of mdn of your choise.

The notification of Mozilla press is an email after the publish of the post.
