### ISSUE TITLE
Rename the plugin

### ISSUE THREAD

**Issue by a2sheppy** [mdn/wp-promote-mdn#61]
It occurred to me the other day that the name "Promote MDN" makes it sound like an advertising tool rather than a helpful addition to a blog or site. The name sounds like it's a promotional tool, and fails to explain what it does in the first place.

I suggest renaming the plugin, perhaps to something like "Web Docs Autolinker" (but hopefully cooler).

**Comment by groovecoder** [comment]
It could be easy to move this to a repo called "wordpress-plugin" under the mdn org on GitHub. But I'm not sure how to go about re-naming a WordPress plugin on the plugin index site. :cry:

**Comment by Mte90** [comment]
Uhm the name on wordpress repo can be change but not the slug.

**Comment by groovecoder** [comment]
As step 1, I've transferred the repo to the "mdn" org: https://github.com/mdn/wp-promote-mdn/

**Comment by Mte90** [comment]
I think that Promote MDN today is the better name for that, the purpose it is not only to get auto link but also promote mdn itself.
