### ISSUE TITLE
Some info about the traffic about that plugin on MDN

### ISSUE THREAD

**Issue by Mte90** [mdn/wp-promote-mdn#80]
cc @groovecoder

**Comment by groovecoder** [comment]
For Oct 4 - Nov 3, MDN received from wordpress blogs' content links from this plugin:

153 sessions, 99 users, 341 pageviews with ...
2.23 pages/session, compared to 1.80 site average
01:49 avg. session duration, compared to 02:24 site average
67.97% bounce rate, compared to 70.41% site average
58.82% new sessions, compared to 38.89% site average

So, the plugin links seem to be good at generating new users who visit more pages, but spend somewhat less time on the site.

**Comment by Waterloo** [comment]
What is the average  session duration people coming from other sources

**Comment by Mte90** [comment]
I think that we need to improve the list of terms with the common terms.
