### ISSUE TITLE
undefined index 'allowcomments' error on every page

### ISSUE THREAD

**Issue by a2sheppy** [mdn/wp-promote-mdn#82]
I have been working on rebuilding my blog (http://www.bitstampede.com/) after a hack last year. After getting Promote MDN reinstalled, it was showing this message on every page:
~~~~
undefined index 'allowcomments' error on every page
~~~~
This field needs to be added to the database the first time you use the addon if it's not already there. Since I didn't upgrade, but reinstalled with a database already in place, any table update process that goes on at install time didn't run, I guess. If you add columns or values to a database or record, they should get inserted when the addon is started up..

**Comment by Mte90** [comment]
https://github.com/mdn/wp-promote-mdn/issues/78
same ticket but plugin is updated only on github.
