### ISSUE TITLE
Separate classes code into its own file to better reading

### ISSUE THREAD

**Issue by Skatox** [mdn/wp-promote-mdn#89]
This doesn't help to the plugin performance, I just wanna say that's better to have each defined class in its own class file (even under `/classes` floder like many plugins), so it's easy to read to the future developer. 
Even, the main.php file could be only includes to the classes files or an autoloader (later is unecessary work for now)

Also, I noticed that some class object are initiated after class definition, I think it's better to have it at the `plugin_loaded` hook, to reduce RAM while the page is loading  plugins.

**Comment by Mte90** [comment]
Yep as I said for #88 the plugin need a reorganize of the code itself.
I was thinking to do it with my boilerplate https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered that will improve the ui and this things.
