### ISSUE TITLE
Parse error in preg_replace_callback

### ISSUE THREAD

**Issue by pa-de-solminihac** [mdn/wp-promote-mdn#90]
Hello,

I just noticed this parse error, that turns my HTTP status code from 200 to 500: 
```
PHP Parse error:  syntax error, unexpected 'GoogleAnalyticsObject' (T_STRING) in /path/to/www/wp-content/plugins/promote-mdn/promote-mdn.php(171) : runtime-created function on line 1
PHP Warning:  preg_replace_callback(): Requires argument 2, '', to be a valid callback in /path/to/www/wp-content/plugins/promote-mdn/promote-mdn.php on line 171
```

Promote-mdn version: 1.8.0
WP version: 4.7.4
PHP version: 5.6

**Comment by Mte90** [comment]
I was thinking that was an issue on my website but I think that is a confilct with another plugin.

To fix in the meanwhile, add to line 168 `if(strpos('GoogleAnalyticsObject', $href)!== false) {` and to line 181 `}`
