### ISSUE TITLE
New readme

### ISSUE THREAD

**Issue by Mte90** [mdn/wp-promote-mdn#94]
We need a more interesting readme for WordPress.

The readme.md is for github and will contain all the stuff for development and the .txt is for WordPress and need more information about can do and about is important with more tags.

**Comment by apoorvasingh17** [comment]
Has this issue been resolved?

**Comment by Mte90** [comment]
No because is part of the milestone 2.0.0 and we need to do that before to work on this, in that way the content will be useful and updated.
